# Generated by Django 5.0.4 on 2024-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=70)),
                ('descricao', models.CharField(default='', max_length=200)),
                ('disponivel', models.BooleanField(default=False)),
            ],
        ),
    ]
